{{- if and (eq .Values.nixery.storageBackend "gcs") .Values.nixery.gcs.createSecret .Values.nixery.gcs.serviceAccountKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nixery.fullname" . }}-gcp-credentials
  labels:
    {{- include "nixery.labels" . | nindent 4 }}
type: Opaque
data:
  service-account.json: {{ .Values.nixery.gcs.serviceAccountKey }}
{{- end }}